services:
  app:
    build: .
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/short_link_development"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: short_link_development
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data:
